### PR TITLE
Add a NuGet sample

### PR DESCRIPTION
**Pull request by guardrex**
Per https://github.com/dotnet/docs/pull/2495#discussion_r127284220

### CODE REVIEW

**Comment by GuardRex** [comment]
@sayedihashimi Could this one be merged (or updated+merged) quickly? ... I'd like to tie it directly into the tutorial topic.

**Review by sayedihashimi — APPROVED** [review]

**Comment by sayedihashimi** [comment]
Sorry for the delay. I missed the pr. I just merged it.

**Comment by neman** [comment]
There are 15 projects following certain name convention and this PR crushed that all!
For example Project names are in the form of `MyProject.Con` and here we have `GarciaSoftware.ConsoleTemplate.CSharp` !
Also `template.json` are following some convention until this PR

```
"name": "Contoso Sample #",
  "identity": "MyProject.#.Sample.CSharp",         
  "groupIdentity":"MyProject.#.Sample",
  "shortName": "sample#",
```

And here we got

```json
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Catalina Garcia",
  "classifications": [ "Common", "Console" ],
  "identity": "GarciaSoftware.ConsoleTemplate.CSharp",
  "name": "Garcia Software Console Application",
  "shortName": "garciaconsole"
}
```

Should contributors follow some rules and naming convention, or is it fine that we write whatever we like?

**Comment by guardrex** [comment]
@neman It happened inadvertently. This is a sample attached to the [Custom Templates topic](https://docs.microsoft.com/dotnet/core/tools/custom-templates) that was dropped in over here *after* that topic and the sample were created. That's why it doesn't match.

@sayedihashimi @mairaw may order some changes to both based on your issue.

**Comment by sayedihashimi** [comment]
Created https://github.com/dotnet/dotnet-template-samples/issues/29 to track getting these updated.

**Pull request merged**
